# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_message.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ml_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_message.proto\x12\x14inboxpert.ml.service\"\xcf\x01\n\x0c\x45mailRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x0e\n\x06sender\x18\x04 \x01(\t\x12\x12\n\nrecipients\x18\x05 \x03(\t\x12@\n\x07headers\x18\x06 \x03(\x0b\x32/.inboxpert.ml.service.EmailRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"G\n\x11\x42\x61tchEmailRequest\x12\x32\n\x06\x65mails\x18\x01 \x03(\x0b\x32\".inboxpert.ml.service.EmailRequest\"\x9d\x01\n\x10\x43\x61tegoryResponse\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08keywords\x18\x04 \x03(\t\x12?\n\x0c\x61lternatives\x18\x05 \x03(\x0b\x32).inboxpert.ml.service.AlternativeCategory\"P\n\x15\x42\x61tchCategoryResponse\x12\x37\n\x07results\x18\x01 \x03(\x0b\x32&.inboxpert.ml.service.CategoryResponse\"<\n\x13\x41lternativeCategory\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfindence\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_EMAILREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_EMAILREQUEST']._serialized_start=43
  _globals['_EMAILREQUEST']._serialized_end=250
  _globals['_EMAILREQUEST_HEADERSENTRY']._serialized_start=204
  _globals['_EMAILREQUEST_HEADERSENTRY']._serialized_end=250
  _globals['_BATCHEMAILREQUEST']._serialized_start=252
  _globals['_BATCHEMAILREQUEST']._serialized_end=323
  _globals['_CATEGORYRESPONSE']._serialized_start=326
  _globals['_CATEGORYRESPONSE']._serialized_end=483
  _globals['_BATCHCATEGORYRESPONSE']._serialized_start=485
  _globals['_BATCHCATEGORYRESPONSE']._serialized_end=565
  _globals['_ALTERNATIVECATEGORY']._serialized_start=567
  _globals['_ALTERNATIVECATEGORY']._serialized_end=627
# @@protoc_insertion_point(module_scope)
