# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ml_message_pb2 as ml__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\x14inboxpert.ml.service\x1a\x10ml_message.proto2\xd8\x01\n\tMLService\x12]\n\x0f\x43\x61tegorizeEmail\x12\".inboxpert.ml.service.EmailRequest\x1a&.inboxpert.ml.service.CategoryResponse\x12l\n\x14\x42\x61tchCategorizeEmail\x12\'.inboxpert.ml.service.BatchEmailRequest\x1a+.inboxpert.ml.service.BatchCategoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MLSERVICE']._serialized_start=61
  _globals['_MLSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
